// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iqeiyqdzdfzorlpynqts.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlxZWl5cWR6ZGZ6b3JscHlucXRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0NDUxMTUsImV4cCI6MjA2MjAyMTExNX0.eOZhpcfSDykBIHkpNPXya_NRsgIOD9evKTHiDfecjU0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);